version: "3"

volumes:
  cctv_manager_volume:

services:
  cctv_manager:
    build: .
    command: ./entrypoint.sh
    container_name: cctv_manager_container
    volumes:
      - cctv_manager_volume:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - TZ=Europe/Moscow
    restart: always
