[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cctv-manager"
version = "0.0.1"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools]
package-dir = {"cctv_manager" = "cctv_manager" }
