# Generated by Django 4.1.9 on 2023-11-19 22:28

import cameras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя камеры')),
                ('configuration', models.JSONField(default=cameras.models.configuration_default, verbose_name='Конфигурация камеры')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
                'ordering': ('name',),
            },
        ),
    ]
