# Generated by Django 4.1.9 on 2023-11-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='ip_address',
            field=models.CharField(max_length=15, unique=True, verbose_name='IP адрес камеры'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя камеры'),
        ),
    ]
