name: Django CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:bookworm
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          sudo mkdir -p /data/config/cctv_manager
          cd cctv_manager
          sudo python utils/secret_generator.py
          python manage.py test
      - name: Prepare to build package
        run: |
          apt update -y
          apt install -y build-essential debhelper dh-python python3-all python3-setuptools python3-django pybuild-plugin-pyproject
      - name: Make deb package
        run: |
          debuild -us -uc
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: cctv-manager_latest.deb
          path: |
            ../*.deb
