name: Django CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:bookworm
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          apt update -y
          apt install -y python3-opencv
      - name: Run Tests
        run: |
          mkdir -p /etc/cctv_manager
          python3 -m cctv_manager.utils.secret_generator
          python3 -m cctv_manager.manage test
      - name: Prepare to build package
        run: |
          apt install -y build-essential debhelper devscripts dh-python python3-all python3-setuptools python3-django pybuild-plugin-pyproject python3-opencv
      - name: Make deb package
        run: |
          debuild -us -uc
          mv ../*.deb ./
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: cctv-manager_latest.deb
          path: |
            *.deb
