name: Django CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          mkdir -p /data/config/cctv_manager
          cd cctv_manager
          python utils/secret_generator.py
          python manage.py test
      - name: Make deb package
        run: |
          ./makedeb.bash
          ls *.deb -l

